// Import product images from assets
import browmapping from "@/assets/images/brow mapping pen.png";
import browsealant from "@/assets/images/brow sealant.png";
import Dbed from "@/assets/images/DBed cover.png";
import DoubleArm from "@/assets/images/Double ARM LIGHT.png";
import Dummyhead from "@/assets/images/Dummy head.png";
import ExScrup from "@/assets/images/ExScrup.png";
import eyePatches from "@/assets/images/eye patch.png";
import Ibprimer from "@/assets/images/Ib primer.png";
import lashbed from "@/assets/images/lash bed.png";
import lashblanket from "@/assets/images/lash bed blanket.png";
import lashwash from "@/assets/images/lash wash brush.png";
import OneBtm from "@/assets/images/One BTM.png";
import twoBtm from "@/assets/images/two btm.png";
import oneBtmCover from "@/assets/images/One BTM cover.png";
import Rqfr from "@/assets/images/Rose QFR.png";
import Igone from "@/assets/images/IG1.png";
import Igtwo from "@/assets/images/IG2.png";
import Igthree from "@/assets/images/IG3.png";
import Igfour from "@/assets/images/IG4.png";
import stool from "@/assets/images/stool.png";
import moonLight from "@/assets/images/moon light tray.png";
import moonLightInches from "@/assets/images/moon light inches.png";
import Glove from "@/assets/images/Glove.png";
import EasyLash from "@/assets/images/Easy lash fan tray.png";
import ClassicLash from "@/assets/images/classic lash fan.png";
import LashGlueTen from "@/assets/images/lash glue ten.png";
import LashGlueFive from "@/assets/images/lash glue five.png";
import LashBreathTape from "@/assets/images/lash breathable table.png";
import LashTransTape from "@/assets/images/lash trans tape.png";
import volumetweazer from "@/assets/images/volume tweezer.png";
import fibertweazer from "@/assets/images/fiber tip tweezer.png";
import lashfan from "@/assets/images/lash fan.png";
import gluering from "@/assets/images/glue ring.png";
import CurvedIsolation from "@/assets/images/curvad isolation.png";
import lashsealant from "@/assets/images/lash sealant.png";
import gluestorage from "@/assets/images/Glue Storage.png";
import Luxuryspa from "@/assets/images/Luxury spa body oil.png";
import Herbalsalt from "@/assets/images/Herbal Bath salts.png";
import Aromatherapy from "@/assets/images/Aromatherapy.png";
import greentea from "@/assets/images/green tea.png";
import claydetox from "@/assets/images/clay detox.png";
import coolingeye from "@/assets/images/cooling eye.png";
import Eucalyptus from "@/assets/images/Eucalyptus.png";
import coconutmilk from "@/assets/images/coconut milk.png";
import footscrub from "@/assets/images/Foot scrub.png";
import silksleep from "@/assets/images/Silk sleep.png";
import Detox from "@/assets/images/Detox.png";
import messagebalm from "@/assets/images/message balm.png";
import hydratingsheet from "@/assets/images/Hydrating sheet.png";
import spaTowelSet from "@/assets/images/spa towel set.png";
import rose from "@/assets/images/rose.png";
import spaIncense from "@/assets/images/spa incense.png";
import luxuryspaGift from "@/assets/images/luxury spa gift.png";
import MastP60 from "@/assets/images/P60.png";
import FandE from "@/assets/images/FandE (1).png";
import GoldenRose from "@/assets/images/GoldenRose.png";
import tag45 from "@/assets/images/tag45.png";
import numb from "@/assets/images/numb.png";
import mastpro from "@/assets/images/mastpro.png";
import mappingstring from "@/assets/images/mapping string.png";

import type { StaticImageData } from "next/image";

export interface PortfolioItem {
  id: string;
  title: string;
  category: 'lashes' | 'nails' | 'tattoos' | 'brows' | 'makeup';
  image: string;
  description: string;
  tags: string[];
  featured: boolean;
  date: string;
}

export interface Product {
  id: string;
  name: string;
  category: 'lashes' | 'nails' | 'tattoos' | 'brows' | 'tools' | 'spa';
  price: number;
  originalPrice?: number;
  image: string | StaticImageData;
  images: (string | StaticImageData)[];
  description: string;
  features: string[];
  inStock: boolean;
  rating: number;
  reviews: number;
  tags: string[];
  featured: boolean;
}

export const portfolioItems: PortfolioItem[] = [
  { id: '1', title: 'Dramatic Volume Lashes', category: 'lashes', image: '/api/placeholder/400/500', description: 'Full volume lash set with dramatic curl and length for special occasions.', tags: ['volume', 'dramatic', 'special occasion'], featured: true, date: '2024-01-15' },
  { id: '2', title: 'Natural Classic Set', category: 'lashes', image: '/api/placeholder/400/500', description: 'Subtle enhancement for everyday wear with natural-looking lashes.', tags: ['natural', 'classic', 'everyday'], featured: false, date: '2024-01-10' },
  { id: '3', title: 'Glamour Nail Art', category: 'nails', image: '/api/placeholder/400/500', description: 'Intricate nail art with rhinestones and metallic accents.', tags: ['glamour', 'rhinestones', 'metallic'], featured: true, date: '2024-01-12' },
  { id: '4', title: 'Minimalist Tattoo Design', category: 'tattoos', image: '/api/placeholder/400/500', description: 'Clean, minimalist tattoo design with fine line work.', tags: ['minimalist', 'fine line', 'clean'], featured: false, date: '2024-01-08' },
  { id: '5', title: 'Perfect Brow Shaping', category: 'brows', image: '/api/placeholder/400/500', description: 'Professional brow shaping and tinting for the perfect arch.', tags: ['shaping', 'tinting', 'professional'], featured: true, date: '2024-01-14' },
  { id: '6', title: 'Bridal Makeup Look', category: 'makeup', image: '/api/placeholder/400/500', description: 'Elegant bridal makeup with long-lasting, photo-ready finish.', tags: ['bridal', 'elegant', 'long-lasting'], featured: true, date: '2024-01-16' },
];

// ── FIX: All product ids are now real MongoDB _id values from the live database ─
export const products: Product[] = [
  // ── TOOLS ──────────────────────────────────────────────────────────────────
  { id: '6a168332d6ac68554de55abd', name: 'Moon Light Tray',                  category: 'tools',   price: 20000,  image: moonLight,      images: [moonLight],               description: 'Professional moon light tray for lash services.',                                                         features: ['Adjustable', 'Professional grade', 'Bright LED', 'Easy to use'],       inStock: true, rating: 4.9, reviews: 127, tags: ['professional', 'lashes', 'equipment'], featured: true },
  { id: '6a168334d6ac68554de55ac0', name: 'Stool',                            category: 'tools',   price: 40000,  image: stool,          images: [stool],                   description: 'Professional salon stool.',                                                                               features: ['Adjustable height', 'Comfortable padding', 'Professional grade', 'Easy to clean'], inStock: true, rating: 4.9, reviews: 89,  tags: ['professional', 'equipment'],           featured: true },
  { id: '6a164c1ea5fceb771c51767e', name: 'Lash Bed',                         category: 'tools',   price: 230000, image: lashbed,        images: [lashbed, lashblanket],    description: 'Professional lash bed for comfortable client positioning during lash extension services.',              features: ['Adjustable height', 'Comfortable padding', 'Professional grade', 'Easy to clean'], inStock: true, rating: 4.5, reviews: 127, tags: ['professional', 'lashes', 'equipment'], featured: true },
  { id: '6a164c1fa5fceb771c517681', name: 'Disposable Bed Cover',             category: 'tools',   price: 24000,  image: Dbed,           images: [Dbed],                    description: 'Hygienic disposable bed cover for maintaining cleanliness during beauty services.',                    features: ['Disposable', 'Hygienic', 'Easy to use', 'Comfortable'],                inStock: true, rating: 4.8, reviews: 89,  tags: ['hygienic', 'disposable', 'professional'], featured: false },
  { id: '6a164c22a5fceb771c51768a', name: 'Glove',                            category: 'tools',   price: 13000,  image: Glove,          images: [Glove],                   description: 'Professional disposable gloves for beauty services.',                                                     features: ['Disposable', 'Hygienic', 'Professional', 'Comfortable'],               inStock: true, rating: 4.9, reviews: 78,  tags: ['professional', 'hygienic'],            featured: false },
  { id: '6a164c31a5fceb771c5176b7', name: 'One Battery Tattoo Machine',       category: 'tools',   price: 55000,  image: OneBtm,         images: [OneBtm, oneBtmCover],     description: 'Professional single battery tattoo machine for precise and consistent work.',                          features: ['Single battery', 'Precise control', 'Professional grade', 'Lightweight'], inStock: true, rating: 4.9, reviews: 78, tags: ['tattoo', 'professional', 'battery'],   featured: false },
  { id: '6a164c32a5fceb771c5176ba', name: 'Two Battery Tattoo Machine',       category: 'tools',   price: 45000,  image: twoBtm,         images: [twoBtm],                  description: 'Dual battery tattoo machine for extended operation and consistent performance.',                        features: ['Dual battery', 'Extended runtime', 'Consistent performance', 'Professional grade'], inStock: true, rating: 4.4, reviews: 92, tags: ['tattoo', 'professional', 'dual battery'], featured: false },
  { id: '6a16833bd6ac68554de55ad2', name: 'Moon Light 26 Inches',             category: 'tools',   price: 130000, image: moonLightInches, images: [moonLight, moonLightInches], description: 'Professional 26-inch moon light tray for lash services.',                                              features: ['Adjustable', 'Professional grade', 'Bright LED', '26 inches'],          inStock: true, rating: 4.5, reviews: 127, tags: ['professional', 'lashes', 'equipment'], featured: true },
  { id: '6a164c1ba5fceb771c517675', name: 'Eye Patch',                        category: 'tools',   price: 5000,   image: eyePatches,     images: [eyePatches],              description: 'Protective eye patches for safe beauty treatments and procedures.',                                     features: ['Protective', 'Comfortable', 'Disposable', 'Safe'],                     inStock: true, rating: 4.4, reviews: 67,  tags: ['protection', 'eye care', 'professional'], featured: false },
  { id: '6a164c1ca5fceb771c517678', name: 'Lash Bed Blanket',                 category: 'tools',   price: 25000,  image: lashblanket,    images: [lashblanket],             description: 'Comfortable blanket for lash bed to enhance client comfort during treatments.',                         features: ['Comfortable', 'Washable', 'Soft material', 'Fits perfectly'],           inStock: true, rating: 4.6, reviews: 89,  tags: ['comfort', 'lashes', 'accessory'],      featured: false },
  { id: '6a164c2fa5fceb771c5176b1', name: 'Brow Mapping Pen',                 category: 'tools',   price: 4500,   image: browmapping,    images: [browmapping],             description: 'Professional brow mapping pen for precise brow design and symmetry.',                                   features: ['Precise marking', 'Water-soluble', 'Professional tool', 'Easy to use'], inStock: true, rating: 4.6, reviews: 112, tags: ['brows', 'professional', 'mapping'],    featured: true },
  { id: '6a164c1da5fceb771c51767b', name: 'Lash Wash Brush',                  category: 'tools',   price: 2000,   image: lashwash,       images: [lashwash],                description: 'Gentle brush for cleaning and maintaining lash extensions.',                                              features: ['Gentle bristles', 'Easy to use', 'Effective cleaning', 'Professional'], inStock: true, rating: 4.8, reviews: 156, tags: ['lashes', 'cleaning', 'maintenance'],   featured: false },
  { id: '6a164c2ea5fceb771c5176ae', name: 'IB Primer',                        category: 'tools',   price: 10000,  image: Ibprimer,       images: [Ibprimer],                description: 'Professional primer for improved product adherence and long-lasting results.',                          features: ['Professional grade', 'Long-lasting', 'Improves adherence', 'Lightweight'], inStock: true, rating: 4.7, reviews: 134, tags: ['primer', 'professional', 'base'],      featured: true },
  { id: '6a164c3ba5fceb771c5176d5', name: 'Brow Sealant',                     category: 'tools',   price: 10000,  image: browsealant,    images: [browsealant],             description: 'Long-lasting brow sealant to keep brows in place all day.',                                               features: ['Long-lasting', 'Waterproof', 'Easy application', 'Natural finish'],    inStock: true, rating: 4.5, reviews: 98,  tags: ['brows', 'sealant', 'styling'],         featured: false },
  { id: '6a168343d6ac68554de55ae7', name: 'Dummy Head',                       category: 'tools',   price: 6500,   image: Dummyhead,      images: [Dummyhead],               description: 'Professional training dummy head for practicing lash and brow techniques.',                             features: ['Training tool', 'Realistic', 'Durable', 'Professional'],               inStock: true, rating: 4.5, reviews: 54,  tags: ['training', 'practice', 'professional'], featured: false },
  { id: '6a168344d6ac68554de55aea', name: 'Double Arm Light',                 category: 'tools',   price: 65000,  image: DoubleArm,      images: [DoubleArm],               description: 'Professional double arm adjustable lighting for optimal visibility during treatments.',                 features: ['Double arm design', 'Adjustable', 'Bright LED', 'Professional grade'], inStock: true, rating: 4.9, reviews: 76,  tags: ['lighting', 'professional', 'adjustable'], featured: true },

  // ── LASHES ─────────────────────────────────────────────────────────────────
  { id: '6a164c1ba5fceb771c517675', name: 'Eye Patch',                        category: 'lashes',  price: 5000,   image: eyePatches,     images: [eyePatches],              description: 'Protective eye patches for safe beauty treatments and procedures.',                                     features: ['Protective', 'Comfortable', 'Disposable', 'Safe'],                     inStock: true, rating: 4.4, reviews: 67,  tags: ['protection', 'eye care', 'professional'], featured: false },
  { id: '6a164c1ca5fceb771c517678', name: 'Lash Bed Blanket',                 category: 'lashes',  price: 25000,  image: lashblanket,    images: [lashblanket],             description: 'Comfortable blanket for lash bed to enhance client comfort during treatments.',                         features: ['Comfortable', 'Washable', 'Soft material', 'Fits perfectly'],           inStock: true, rating: 4.6, reviews: 89,  tags: ['comfort', 'lashes', 'accessory'],      featured: false },
  { id: '6a164c2fa5fceb771c5176b1', name: 'Brow Mapping Pen',                 category: 'lashes',  price: 4500,   image: browmapping,    images: [browmapping],             description: 'Professional brow mapping pen for precise brow design and symmetry.',                                   features: ['Precise marking', 'Water-soluble', 'Professional tool', 'Easy to use'], inStock: true, rating: 4.6, reviews: 112, tags: ['brows', 'professional', 'mapping'],    featured: true },
  { id: '6a164c1da5fceb771c51767b', name: 'Lash Wash Brush',                  category: 'lashes',  price: 2000,   image: lashwash,       images: [lashwash],                description: 'Gentle brush for cleaning and maintaining lash extensions.',                                              features: ['Gentle bristles', 'Easy to use', 'Effective cleaning', 'Professional'], inStock: true, rating: 4.8, reviews: 156, tags: ['lashes', 'cleaning', 'maintenance'],   featured: false },
  { id: '6a164c1ea5fceb771c51767e', name: 'Lash Bed',                         category: 'lashes',  price: 230000, image: lashbed,        images: [lashbed, lashblanket],    description: 'Professional lash bed for comfortable client positioning during lash extension services.',              features: ['Adjustable height', 'Comfortable padding', 'Professional grade', 'Easy to clean'], inStock: true, rating: 4.5, reviews: 127, tags: ['professional', 'lashes', 'equipment'], featured: true },
  { id: '6a164c1fa5fceb771c517681', name: 'Disposable Bed Cover',             category: 'lashes',  price: 24000,  image: Dbed,           images: [Dbed],                    description: 'Hygienic disposable bed cover for maintaining cleanliness during beauty services.',                    features: ['Disposable', 'Hygienic', 'Easy to use', 'Comfortable'],                inStock: true, rating: 4.8, reviews: 89,  tags: ['hygienic', 'disposable', 'professional'], featured: false },
  { id: '6a164c20a5fceb771c517684', name: 'Easy Lash Fan Tray',               category: 'lashes',  price: 9000,   image: EasyLash,       images: [EasyLash],                description: 'Easy lash fan tray for professional lash application.',                                                   features: ['Disposable', 'Hygienic', 'Easy to use', 'Comfortable'],                inStock: true, rating: 4.8, reviews: 89,  tags: ['hygienic', 'disposable', 'professional'], featured: false },
  { id: '6a164c21a5fceb771c517687', name: 'Classic Lash Fan',                 category: 'lashes',  price: 9000,   image: ClassicLash,    images: [ClassicLash],             description: 'Classic lash fan for professional lash application.',                                                     features: ['Disposable', 'Hygienic', 'Easy to use', 'Comfortable'],                inStock: true, rating: 4.8, reviews: 89,  tags: ['hygienic', 'disposable', 'professional'], featured: false },
  { id: '6a164c22a5fceb771c51768a', name: 'Glove',                            category: 'lashes',  price: 13000,  image: Glove,          images: [Glove],                   description: 'Professional disposable gloves for lash services.',                                                       features: ['Disposable', 'Hygienic', 'Easy to use', 'Comfortable'],                inStock: true, rating: 4.8, reviews: 89,  tags: ['hygienic', 'disposable', 'professional'], featured: false },
  { id: '6a164c23a5fceb771c51768d', name: 'Lash Glue 10ml',                   category: 'lashes',  price: 20000,  image: LashGlueTen,    images: [LashGlueTen],             description: 'Professional lash glue 10ml for long-lasting lash extensions.',                                           features: ['Professional grade', 'Long-lasting', 'Strong hold', '10ml'],            inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'glue', 'professional'],      featured: false },
  { id: '6a164c24a5fceb771c517690', name: 'Lash Glue 5ml',                    category: 'lashes',  price: 16000,  image: LashGlueFive,   images: [LashGlueFive],            description: 'Professional lash glue 5ml for lash extensions.',                                                         features: ['Professional grade', 'Long-lasting', 'Strong hold', '5ml'],             inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'glue', 'professional'],      featured: false },
  { id: '6a164c25a5fceb771c517693', name: 'Lash Breathable Tape',             category: 'lashes',  price: 1200,   image: LashBreathTape, images: [LashBreathTape],          description: 'Breathable tape for lash extension application.',                                                         features: ['Breathable', 'Hygienic', 'Easy to use', 'Comfortable'],                inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'tape', 'professional'],      featured: false },
  { id: '6a164c26a5fceb771c517696', name: 'Lash Transparent Tape',            category: 'lashes',  price: 1000,   image: LashTransTape,  images: [LashTransTape],           description: 'Transparent tape for lash extension application.',                                                        features: ['Transparent', 'Hygienic', 'Easy to use', 'Comfortable'],               inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'tape', 'professional'],      featured: false },
  { id: '6a164c27a5fceb771c517699', name: 'Volume Tweezer',                   category: 'lashes',  price: 7500,   image: volumetweazer,  images: [volumetweazer],           description: 'Professional volume tweezer for lash extensions.',                                                        features: ['Precision tips', 'Lightweight', 'Professional grade', 'Durable'],      inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'tweezer', 'professional'],   featured: false },
  { id: '6a164c28a5fceb771c51769c', name: 'Fiber Tip Tweezer',                category: 'lashes',  price: 8000,   image: fibertweazer,   images: [fibertweazer],            description: 'Professional fiber tip tweezer for lash extensions.',                                                     features: ['Fiber tips', 'Lightweight', 'Professional grade', 'Durable'],           inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'tweezer', 'professional'],   featured: false },
  { id: '6a164c29a5fceb771c51769f', name: 'Lash Fan',                         category: 'lashes',  price: 6500,   image: lashfan,        images: [lashfan],                 description: 'Professional lash fan for lash extension application.',                                                    features: ['Lightweight', 'Easy to use', 'Professional grade', 'Durable'],          inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'fan', 'professional'],       featured: false },
  { id: '6a164c2aa5fceb771c5176a2', name: 'Glue Ring',                        category: 'lashes',  price: 5000,   image: gluering,       images: [gluering],                description: 'Glue ring for lash extension application.',                                                               features: ['Disposable', 'Hygienic', 'Easy to use', 'Comfortable'],                inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'glue', 'professional'],      featured: false },
  { id: '6a164c2ba5fceb771c5176a5', name: 'Curved Isolation Tweezer',         category: 'lashes',  price: 7000,   image: CurvedIsolation, images: [CurvedIsolation],        description: 'Curved isolation tweezer for precise lash extension application.',                                         features: ['Curved tips', 'Lightweight', 'Professional grade', 'Durable'],          inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'tweezer', 'professional'],   featured: false },
  { id: '6a164c2ca5fceb771c5176a8', name: 'Lash Sealant',                     category: 'lashes',  price: 8000,   image: lashsealant,    images: [lashsealant],             description: 'Professional lash sealant for long-lasting lash extensions.',                                             features: ['Long-lasting', 'Professional grade', 'Easy application', 'Protective'], inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'sealant', 'professional'],   featured: false },
  { id: '6a164c2da5fceb771c5176ab', name: 'Glue Storage',                     category: 'lashes',  price: 5000,   image: gluestorage,    images: [gluestorage],             description: 'Professional glue storage for lash extension adhesives.',                                                 features: ['Airtight', 'Professional grade', 'Easy to use', 'Durable'],            inStock: true, rating: 4.8, reviews: 89,  tags: ['lashes', 'storage', 'professional'],   featured: false },
  { id: '6a164c2ea5fceb771c5176ae', name: 'IB Primer',                        category: 'lashes',  price: 10000,  image: Ibprimer,       images: [Ibprimer],                description: 'Professional primer for improved lash adhesion and long-lasting results.',                                 features: ['Professional grade', 'Long-lasting', 'Improves adherence', 'Lightweight'], inStock: true, rating: 4.7, reviews: 134, tags: ['primer', 'professional', 'base'],      featured: true },

  // ── TATTOOS ────────────────────────────────────────────────────────────────
  { id: '6a164c30a5fceb771c5176b4', name: 'Mast P60 Machine',                 category: 'tattoos', price: 450000, image: MastP60,        images: [MastP60],                 description: 'Professional Mast P60 tattoo machine.',                                                                  features: ['Professional grade', 'Precise control', 'Lightweight', 'Durable'],     inStock: true, rating: 4.5, reviews: 54,  tags: ['tattoo', 'machine', 'professional'],   featured: false },
  { id: '6a164c31a5fceb771c5176b7', name: 'One Battery Tattoo Machine',       category: 'tattoos', price: 55000,  image: OneBtm,         images: [OneBtm, oneBtmCover],     description: 'Professional single battery tattoo machine for precise and consistent work.',                          features: ['Single battery', 'Precise control', 'Professional grade', 'Lightweight'], inStock: true, rating: 4.9, reviews: 78, tags: ['tattoo', 'professional', 'battery'],   featured: true },
  { id: '6a164c32a5fceb771c5176ba', name: 'Two Battery Tattoo Machine',       category: 'tattoos', price: 45000,  image: twoBtm,         images: [twoBtm],                  description: 'Dual battery tattoo machine for extended operation and consistent performance.',                        features: ['Dual battery', 'Extended runtime', 'Consistent performance', 'Professional grade'], inStock: true, rating: 4.4, reviews: 92, tags: ['tattoo', 'professional', 'dual battery'], featured: false },
  { id: '6a164c33a5fceb771c5176bd', name: 'One Battery Tattoo Machine Cover', category: 'tattoos', price: 500,    image: oneBtmCover,    images: [oneBtmCover],             description: 'Protective cover for one battery tattoo machine to maintain hygiene.',                                  features: ['Protective', 'Hygienic', 'Easy to clean', 'Fits perfectly'],            inStock: true, rating: 4.2, reviews: 145, tags: ['tattoo', 'accessory', 'hygienic'],     featured: false },
  { id: '6a164c34a5fceb771c5176c0', name: 'F&E Primary Cream',                category: 'tattoos', price: 18000,  image: FandE,          images: [FandE],                   description: 'F&E primary cream for tattoo procedures.',                                                                features: ['Professional grade', 'Effective', 'Easy to use', 'Safe'],               inStock: true, rating: 4.2, reviews: 145, tags: ['tattoo', 'cream', 'professional'],     featured: false },
  { id: '6a164c35a5fceb771c5176c3', name: 'Golden Rose Anesthe',              category: 'tattoos', price: 10000,  image: GoldenRose,     images: [GoldenRose],              description: 'Golden Rose anaesthetic cream for tattoo procedures.',                                                    features: ['Anaesthetic', 'Professional grade', 'Effective', 'Safe'],               inStock: true, rating: 4.2, reviews: 145, tags: ['tattoo', 'anaesthetic', 'professional'], featured: false },
  { id: '6a164c36a5fceb771c5176c6', name: 'Tag 45 Secondary Numb',            category: 'tattoos', price: 15000,  image: tag45,          images: [tag45],                   description: 'Tag 45 secondary numbing cream for tattoo procedures.',                                                   features: ['Numbing', 'Professional grade', 'Effective', 'Safe'],                   inStock: true, rating: 4.2, reviews: 145, tags: ['tattoo', 'numbing', 'professional'],   featured: false },
  { id: '6a164c37a5fceb771c5176c9', name: 'Primary Numb Cream',               category: 'tattoos', price: 15000,  image: numb,           images: [numb],                    description: 'Primary numbing cream for tattoo procedures.',                                                            features: ['Numbing', 'Professional grade', 'Effective', 'Safe'],                   inStock: true, rating: 4.2, reviews: 145, tags: ['tattoo', 'numbing', 'professional'],   featured: false },
  { id: '6a164c38a5fceb771c5176cc', name: 'Mast Pro Cartridge 20pcs',         category: 'tattoos', price: 28000,  image: mastpro,        images: [mastpro],                 description: 'Mast Pro tattoo cartridges, pack of 20.',                                                                 features: ['Pack of 20', 'Professional grade', 'Precise', 'Compatible'],            inStock: true, rating: 4.2, reviews: 145, tags: ['tattoo', 'cartridge', 'professional'], featured: false },
  { id: '6a164c39a5fceb771c5176cf', name: 'Mapping Strings',                  category: 'tattoos', price: 15000,  image: mappingstring,  images: [mappingstring],           description: 'Professional mapping strings for tattoo and brow procedures.',                                            features: ['Professional grade', 'Precise', 'Easy to use', 'Durable'],              inStock: true, rating: 4.2, reviews: 145, tags: ['tattoo', 'mapping', 'professional'],   featured: false },

  // ── BROWS ──────────────────────────────────────────────────────────────────
  { id: '6a164c2fa5fceb771c5176b1', name: 'Brow Mapping Pen',                 category: 'brows',   price: 4500,   image: browmapping,    images: [browmapping],             description: 'Professional brow mapping pen for precise brow design and symmetry.',                                   features: ['Precise marking', 'Water-soluble', 'Professional tool', 'Easy to use'], inStock: true, rating: 4.6, reviews: 112, tags: ['brows', 'professional', 'mapping'],    featured: true },
  { id: '6a164c3ba5fceb771c5176d5', name: 'Brow Sealant',                     category: 'brows',   price: 10000,  image: browsealant,    images: [browsealant],             description: 'Long-lasting brow sealant to keep brows in place all day.',                                               features: ['Long-lasting', 'Waterproof', 'Easy application', 'Natural finish'],    inStock: true, rating: 4.5, reviews: 98,  tags: ['brows', 'sealant', 'styling'],         featured: false },

  // ── SPA ────────────────────────────────────────────────────────────────────
  { id: '6a164c3ca5fceb771c5176d8', name: 'Luxury Spa Body Oil',              category: 'spa',     price: 18000,  image: Luxuryspa,      images: [Luxuryspa],               description: 'Luxury spa body oil for smooth, radiant skin.',                                                           features: ['Natural ingredients', 'Moisturizing', 'All skin types', 'Luxury'],      inStock: true, rating: 4.3, reviews: 156, tags: ['skincare', 'body care', 'spa'],        featured: true },
  { id: '6a164c3da5fceb771c5176db', name: 'Herbal Bath Salt',                 category: 'spa',     price: 12500,  image: Herbalsalt,     images: [Herbalsalt],              description: 'Herbal bath salts for a relaxing spa experience.',                                                        features: ['Natural herbs', 'Relaxing', 'Moisturizing', 'All skin types'],          inStock: true, rating: 4.3, reviews: 156, tags: ['skincare', 'bath', 'spa'],             featured: true },
  { id: '6a164c3ea5fceb771c5176de', name: 'Aromatherapy Candle',              category: 'spa',     price: 10000,  image: Aromatherapy,   images: [Aromatherapy],            description: 'Aromatherapy candle for a relaxing spa atmosphere.',                                                      features: ['Natural wax', 'Long-lasting', 'Relaxing scent', 'Handmade'],            inStock: true, rating: 4.3, reviews: 156, tags: ['aromatherapy', 'candle', 'spa'],       featured: true },
  { id: '6a164c3fa5fceb771c5176e1', name: 'Green Tea Facial Mask',            category: 'spa',     price: 14000,  image: greentea,       images: [greentea],                description: 'Green tea facial mask for glowing skin.',                                                                 features: ['Green tea extract', 'Antioxidant', 'All skin types', 'Brightening'],    inStock: true, rating: 4.3, reviews: 156, tags: ['skincare', 'facial', 'spa'],           featured: true },
  { id: '6a164c40a5fceb771c5176e4', name: 'Exfoliating Body Scrub',           category: 'spa',     price: 14000,  image: ExScrup,        images: [ExScrup],                 description: 'Gentle exfoliating body scrub for smooth, radiant skin.',                                                 features: ['Gentle exfoliation', 'Moisturizing', 'Natural ingredients', 'All skin types'], inStock: true, rating: 4.3, reviews: 156, tags: ['skincare', 'exfoliating', 'body care'], featured: true },
  { id: '6a164c41a5fceb771c5176e7', name: 'Rose Quartz Facial Roll',          category: 'spa',     price: 12000,  image: Rqfr,           images: [Rqfr],                    description: 'Premium rose quartz facial roller for reducing puffiness and promoting circulation.',                    features: ['Rose quartz', 'Dual-sided', 'Promotes circulation', 'Reduces puffiness'], inStock: true, rating: 4.7, reviews: 203, tags: ['facial', 'skincare', 'massage'],      featured: false },
  { id: '6a164c42a5fceb771c5176ea', name: 'Clay Detox Mask',                  category: 'spa',     price: 13000,  image: claydetox,      images: [claydetox],               description: 'Clay detox mask for deep cleansing and purifying skin.',                                                  features: ['Deep cleansing', 'Detoxifying', 'All skin types', 'Natural clay'],      inStock: true, rating: 4.7, reviews: 134, tags: ['skincare', 'detox', 'spa'],            featured: true },
  { id: '6a164c43a5fceb771c5176ed', name: 'Cooling Eye Gel Pad',              category: 'spa',     price: 11000,  image: coolingeye,     images: [coolingeye],              description: 'Cooling eye gel pad for reducing puffiness and dark circles.',                                            features: ['Cooling', 'Reduces puffiness', 'Hygienic', 'Easy to use'],              inStock: true, rating: 4.8, reviews: 89,  tags: ['eye care', 'skincare', 'spa'],         featured: false },
  { id: '6a164c44a5fceb771c5176f0', name: 'Eucalyptus Shower Steamer',        category: 'spa',     price: 10000,  image: Eucalyptus,     images: [Eucalyptus],              description: 'Eucalyptus shower steamer for a refreshing spa experience.',                                              features: ['Eucalyptus', 'Refreshing', 'Natural', 'Easy to use'],                   inStock: true, rating: 4.8, reviews: 89,  tags: ['shower', 'aromatherapy', 'spa'],       featured: false },
  { id: '6a164c45a5fceb771c5176f3', name: 'Coconut Milk Bath Soak',           category: 'spa',     price: 16000,  image: coconutmilk,    images: [coconutmilk],             description: 'Coconut milk bath soak for soft, moisturised skin.',                                                      features: ['Coconut milk', 'Moisturizing', 'Relaxing', 'All skin types'],           inStock: true, rating: 4.8, reviews: 89,  tags: ['bath', 'skincare', 'spa'],             featured: false },
  { id: '6a164c46a5fceb771c5176f6', name: 'Luxury Foot Scrub',                category: 'spa',     price: 13000,  image: footscrub,      images: [footscrub],               description: 'Luxury foot scrub for smooth, soft feet.',                                                                features: ['Exfoliating', 'Moisturizing', 'Natural ingredients', 'Refreshing'],     inStock: true, rating: 4.8, reviews: 89,  tags: ['foot care', 'skincare', 'spa'],        featured: false },
  { id: '6a164c47a5fceb771c5176f9', name: 'Silk Sleep Mask',                  category: 'spa',     price: 10500,  image: silksleep,      images: [silksleep],               description: 'Silk sleep mask for a restful night\'s sleep.',                                                           features: ['Silk material', 'Comfortable', 'Blocks light', 'Adjustable'],           inStock: true, rating: 4.8, reviews: 89,  tags: ['sleep', 'skincare', 'spa'],            featured: false },
  { id: '6a164c48a5fceb771c5176fc', name: 'Detox Herbal Tea Blend',           category: 'spa',     price: 11000,  image: Detox,          images: [Detox],                   description: 'Detox herbal tea blend for a healthy, refreshing drink.',                                                 features: ['Natural herbs', 'Detoxifying', 'Refreshing', 'Healthy'],                inStock: true, rating: 4.8, reviews: 89,  tags: ['tea', 'detox', 'spa'],                 featured: false },
  { id: '6a164c49a5fceb771c5176ff', name: 'Body Massage Balm',                category: 'spa',     price: 16000,  image: messagebalm,    images: [messagebalm],             description: 'Body massage balm for relaxing and soothing tired muscles.',                                              features: ['Natural ingredients', 'Soothing', 'Moisturizing', 'Relaxing'],          inStock: true, rating: 4.8, reviews: 89,  tags: ['massage', 'body care', 'spa'],         featured: false },
  { id: '6a164c4aa5fceb771c517702', name: 'Hydrating Sheet Mask',             category: 'spa',     price: 14000,  image: hydratingsheet, images: [hydratingsheet],          description: 'Hydrating sheet mask for glowing, moisturised skin.',                                                     features: ['Hydrating', 'All skin types', 'Easy to use', 'Brightening'],            inStock: true, rating: 4.8, reviews: 89,  tags: ['skincare', 'facial', 'spa'],           featured: false },
  { id: '6a164c4ba5fceb771c517705', name: 'Luxury Spa Towel Set',             category: 'spa',     price: 20000,  image: spaTowelSet,    images: [spaTowelSet],             description: 'Luxury spa towel set for a professional spa experience.',                                                 features: ['Soft material', 'Absorbent', 'Luxury', 'Professional'],                 inStock: true, rating: 4.8, reviews: 89,  tags: ['towel', 'luxury', 'spa'],              featured: false },
  { id: '6a164c4ca5fceb771c517708', name: 'Rose Infused Toner Mist',          category: 'spa',     price: 14000,  image: rose,           images: [rose],                    description: 'Rose infused toner mist for hydrated, glowing skin.',                                                     features: ['Rose extract', 'Hydrating', 'All skin types', 'Refreshing'],            inStock: true, rating: 4.8, reviews: 89,  tags: ['skincare', 'toner', 'spa'],            featured: false },
  { id: '6a164c4da5fceb771c51770b', name: 'Spa Incense Sticks',               category: 'spa',     price: 10000,  image: spaIncense,     images: [spaIncense],              description: 'Spa incense sticks for a relaxing atmosphere.',                                                           features: ['Natural', 'Long-lasting', 'Relaxing scent', 'Hand-rolled'],             inStock: true, rating: 4.8, reviews: 89,  tags: ['aromatherapy', 'incense', 'spa'],      featured: false },
  { id: '6a164c4ea5fceb771c51770e', name: 'Luxury Spa Gift Set',              category: 'spa',     price: 28000,  image: luxuryspaGift,  images: [luxuryspaGift],           description: 'Luxury spa gift set — the perfect treat.',                                                                features: ['Gift set', 'Luxury', 'Multiple products', 'Perfect gift'],              inStock: true, rating: 4.8, reviews: 89,  tags: ['gift', 'luxury', 'spa'],               featured: false },
];

export const categories = [
  { id: 'all',     name: 'All',    count: portfolioItems.length },
  { id: 'lashes',  name: 'Lashes', count: portfolioItems.filter(item => item.category === 'lashes').length },
  { id: 'nails',   name: 'Nails',  count: portfolioItems.filter(item => item.category === 'nails').length },
  { id: 'tattoos', name: 'Tattoos',count: portfolioItems.filter(item => item.category === 'tattoos').length },
  { id: 'brows',   name: 'Brows',  count: portfolioItems.filter(item => item.category === 'brows').length },
  { id: 'makeup',  name: 'Makeup', count: portfolioItems.filter(item => item.category === 'makeup').length },
];